server:
  port: 8102

spring:
  application:
    name: provider1
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
    register-with-eureka: true
    fetch-registry: true

